// Auto-generated Supabase Configuration
// Generated by build.js - Do not edit manually

const SUPABASE_URL = "https://fryuyoxndikjhykjwpze.supabase.co";
const SUPABASE_ANON_KEY = "sb_publishable_rX3KFlW6MF9B2J5yXnu6Bg_DLtSlBU9you-anon-key";

// Set on window for global frontend access
window.SUPABASE_URL = SUPABASE_URL;
window.SUPABASE_ANON_KEY = SUPABASE_ANON_KEY;
window.useMockData = SUPABASE_URL.includes("your-project-id") || !SUPABASE_URL;

if (typeof supabase !== 'undefined' && !window.useMockData) {
  window.supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
} else {
  window.supabaseClient = null;
  console.warn("Using offline mock database mode (Supabase URL/Key environment variables are placeholders).");
}
