const fs = require('fs');
const path = require('path');

// Basic parser for local .env files (zero dependencies)
let env = {};
const envPath = path.join(__dirname, '.env');
if (fs.existsSync(envPath)) {
  const content = fs.readFileSync(envPath, 'utf8');
  content.split('\n').forEach(line => {
    const parts = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
    if (parts) {
      const key = parts[1];
      let value = parts[2] || '';
      // Trim quotes if wrapped
      if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);
      if (value.startsWith("'") && value.endsWith("'")) value = value.slice(1, -1);
      env[key] = value.trim();
    }
  });
}

// Get keys from system process env (Vercel) or local .env fallback
const supabaseUrl = process.env.SUPABASE_URL || env.SUPABASE_URL || 'https://your-project-id.supabase.co';
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || env.SUPABASE_ANON_KEY || 'your-anon-key';

const configContent = `// Auto-generated Supabase Configuration
// Generated by build.js - Do not edit manually

const SUPABASE_URL = "${supabaseUrl}";
const SUPABASE_ANON_KEY = "${supabaseAnonKey}";

// Set on window for global frontend access
window.SUPABASE_URL = SUPABASE_URL;
window.SUPABASE_ANON_KEY = SUPABASE_ANON_KEY;
window.useMockData = SUPABASE_URL.includes("your-project-id") || !SUPABASE_URL;

if (typeof supabase !== 'undefined' && !window.useMockData) {
  window.supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
} else {
  window.supabaseClient = null;
  console.warn("Using offline mock database mode (Supabase URL/Key environment variables are placeholders).");
}
`;

// Ensure target directory exists
const supabaseDir = path.join(__dirname, 'supabase');
if (!fs.existsSync(supabaseDir)) {
  fs.mkdirSync(supabaseDir, { recursive: true });
}

fs.writeFileSync(path.join(supabaseDir, 'config.js'), configContent);
console.log('Successfully generated supabase/config.js from environment!');
